"""Database management package for SQLite operations."""

from .db_manager import (
    init_db,
    upsert_courses,
    get_courses,
    upsert_assignments,
    get_assignments_for_week,
    get_assignments_for_week_with_ids,
    get_all_assignments,
    upsert_study_plan,
    get_study_plans_for_week,
    get_user_plans_for_week_detailed,
    set_assignment_completed,
    get_week_assignments_with_status,
    get_pending_reminders,
    mark_reminder_sent,
    update_study_plan_time,
    get_pending_due_date_reminders,
    mark_due_date_reminder_sent,
    check_week_completion,
    get_week_completion_notified,
    mark_week_completion_notified,
)

__all__ = [
    'init_db',
    'upsert_courses',
    'get_courses',
    'upsert_assignments',
    'get_assignments_for_week',
    'get_assignments_for_week_with_ids',
    'get_all_assignments',
    'upsert_study_plan',
    'get_study_plans_for_week',
    'get_user_plans_for_week_detailed',
    'set_assignment_completed',
    'get_week_assignments_with_status',
    'get_pending_reminders',
    'mark_reminder_sent',
    'update_study_plan_time',
    'get_pending_due_date_reminders',
    'mark_due_date_reminder_sent',
    'check_week_completion',
    'get_week_completion_notified',
    'mark_week_completion_notified',
]
